### PR TITLE
#129 - Fix uploading unnormalised paths

### LINKED ISSUE #129: Document upload does not support `./` in it's path
When I want to upload documents, paths with `./` (local directory) are not picked up. This is easy to reproduce:

```
*** Settings ***
Library             Camunda
Library             Camunda.FileSystem

*** Tasks ***
Test
    Create File    ./test.txt
    Upload Documents    ./test.txt     variableName=fullPath
    # returns empty array
  
    Upload Documents    test.txt     variableName=noPrefix
    # Returns file descriptor
```

This leads to unintuitive behavior when we get paths as outputs from previous steps. E.g., when handling screenshots from Selenium:

```
*** Settings ***
Library             Camunda.Browser.Selenium
Library             Camunda

*** Tasks ***
Test
    Open Available Browser   about:blank
    ${location}=    Screenshot
    # ${location} = ./screenshot-1741680988-page.png
    Upload Documents    ${location}     variableName=screenshot
    # Does not upload the file, even if it is present
    Close All Browsers
```

### PR DESCRIPTION
**Pull request by Poundex**
Fixes #129

### CODE REVIEW

File: rpa-worker-application/src/functionalTest/groovy/io/camunda/rpa/worker/files/api/FilesFunctionalSpec.groovy [hunk 1]
```diff
@@ -13,18 +14,23 @@ import okhttp3.MediaType
...
 import org.springframework.web.reactive.function.BodyInserters
 import org.springframework.web.util.UriComponentsBuilder
 import reactor.core.publisher.Mono
+import spock.lang.Issue
 
 import java.nio.file.Files
+import java.time.Duration
 import java.util.concurrent.TimeUnit
 
+@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
```
Comment (Poundex) [inline rpa-worker-application/src/functionalTest/groovy/io/camunda/rpa/worker/files/api/FilesFunctionalSpec.groovy:33]: **camunda-utils** is going allow setting the Worker endpoint with an env var so this port pinning will not be necessary

File: rpa-worker-application/src/functionalTest/groovy/io/camunda/rpa/worker/files/api/FilesFunctionalSpec.groovy [hunk 2]
```diff
@@ -246,4 +198,90 @@ Do Nothing
...
+		and:
+		zeebeApi.dispatcher = this.&copyInputToOutputDispatcher
+
+		when:
+		EvaluateScriptResponse response = post()
+				.uri("/script/evaluate")
+				.body(BodyInserters.fromValue(new EvaluateScriptRequest(UPLOAD_FILES_WITH_UNNORMALISED_PATHS_SCRIPT, [:])))
+				.retrieve()
+				.bodyToMono(EvaluateScriptResponse)
+				.block(Duration.ofSeconds(10))
```
Comment (Poundex) [inline rpa-worker-application/src/functionalTest/groovy/io/camunda/rpa/worker/files/api/FilesFunctionalSpec.groovy:237]: This increased timeout will not be necessary, the delay is caused by the way hostname resolution works in Python on Windows. **camunda-utils** is going to change the default Worker URL to use an IP address instead so this request can use the normal timeout mechanism once the lib is updated

**Comment by Poundex** [comment]
Relates https://github.com/camunda/rpa-python-libraries/issues/7
